---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hello-world-sealed-secret
  namespace: dev
spec:
  encryptedData:
    password: AgCG7d4+HAoPwe2dtex342hbIHVZ//0EceSB5TkzN3mhNJst3NX1rKv/+SEbk+B8vPpj6+hksV/ZgG5D0RklklE1FRmKadHXPx6VqGwRyBcwnctzRsCG9BnXKP4uqXfwCnDooABuozbr31+QuXA2VVS3videsEdzHfPWbKBIZt7UXt1+TEFJ3AWKIx0ymrKwy5EccBMsrFAh0lozTemUd66WudGvVcne3ZA3Pi/M+P5K8E93hW+BhTs4WISMcNpuOCgHaY+I61+jsnwRGJxTWJV+iLqt88kW2rOktAMosQwqgJua43ibVrgiyRl86QYYMKW/TcGmTe2qpC47t8CiDKDENEMZGlF5oLrMxnPHpYiOLdENxe62WFcoMi7j+DrrMsag/Ry0Q3tXLjelLI4xqX1kHyRbz7kCY//m1o7mOEG3bLMWVa8uTfqFpD5jnG39At/1KfniyL5S/nx+N8cg17/IKKfOwZSkGugSciLzc1FJPfG5R0yybV9ipIMrO+kgk/dC3yuDYnXaBPkycsGMculuB0zUdEMBDFYPUMxsH8fPDTDRC/+sE853amA08qaSOE4lJjVAmIZGhSlOzj2IH0mNokqZ9VkD4PcGLMKQ3sGbEdnEt+dRQ4jejxXPeT9cuqsJmWTXxXpS4WaR1feKZ9NVmdOz3suDtSle1had5uJh6aR5VFQlulS6BuNCcNqdMeAEUU/NY1hl6xQqb8/XYw==
    username: AgADPC1ynkfSySUigi8fMBzASpVVjJs2N5KkxoIJcMcJWoJUZH0ttYknytPl9TDFlFbcVuJn2eexHhlpchj79Z7CDzxuLOppC6S01LO667zgyX/meFc/RevHItPvRVP6XMw8nmq94aVOD7UwB0THtxh8XwK+zgtyzM+3Qj12wgsxR08TMXsrPbsko8IFgonNF+JEVT3PSTm0elyR1qV+ax9n71OV4k5Hhdm4wt+/pi39hWmAWuY6sne3tzIHZI1iUxfh2+WEPgqHMqbEnGYyuQlgTK8iiduvRoB4Kp0mYpHPPYadvBaHsB3QyFffZQDXPY4a80KPWykM1EtC0/h+IkUtqxTMzFvoKzpapKBI2kYTk5ZQCubscxpjsX3TEMEsx/G0fq4JfhA87fWcCYiuM5Q38UrwnIO43BYBcd7tenhZHawG9Ddtn4xv/zx8NGdIweqMQhje/IuTGJEYFhmi4t2MdOGD+NGG4lLkU8hGyiQKd446RerqQ/mEV1kQhNBzmZvnsaJYUXWs6tLFVh65Ce/adh9H2wMTRxAXC3eQXGdaaBqwJJ9+KwUQ1NjfCBdZckI0Ez6edEMx7YNXUxcpOpx7OzGREIV0d9ER7UYJGYawscnyZcpsVuKGqHXicjljukpCypCwmz2hH297Mf4zLh+NID6LHdXzs/LV/Cc1w823srFyCpSRjNQH3Hm9l/8GOTHFu3SdusY0
  template:
    metadata:
      name: hello-world-secret
      namespace: dev
    type: Opaque
